Add button/menu item for data stream notifications collection page #539
farmOS/farmOS pull request #555
Opened 2022-08-06 20:52 UTC by Farmer-Eds-Shed

Add button/menu item for data stream notifications collection page #539

Adds to settings menu
![image](https://user-images.githubusercontent.com/63633329/183265494-3014b5e9-7cda-4f1f-9120-4245d99d4f2d.png)

2022-08-07 11:50 UTC, mstenta commented
Looks OK to me! Requesting @paul121's review since he is more familiar with data streams.

One small thought (not a blocker): I could see this being a sub-tab of a new general "Notifications" tab in the future, which may also include other notification type settings (eg: worker task notifications).

FYI I'll plan to rebase and squash these commits before merging.

2022-08-07 13:05 UTC, Farmer-Eds-Shed commented
I'll not be offended if it's better suited elsewhere, was bugging me with having nowhere though.
Funny enough I had considered a new notifications tab as I am also working on some notifications modules that could occupy a sub tab.

2022-08-07 13:16 UTC, mstenta commented
> Funny enough I had considered a new notifications tab as I am also working on some notifications modules that could occupy a sub tab.

The main question is: what module should be responsible for the "Notifications" tab, if multiple modules need to rely on it. Doesn't make sense to have it in the Data Stream module. And we don't really want it to show up all the time, otherwise it would be empty without any child tabs.

2022-08-07 13:55 UTC, Farmer-Eds-Shed commented
Could it not just be it's own module in this case? Not installed by default but required by any new notifications module.

2022-08-08 19:12 UTC, paul121 commented
Interesting thanks for working on this @Farmer-Eds-Shed !! My first thought is that this seems a little weird in the Settings pages, but it's not awful. Agree that it would look better under a "Notifications" tab...

> The main question is: what module should be responsible for the "Notifications" tab, if multiple modules need to rely on it. Doesn't make sense to have it in the Data Stream module. And we don't really want it to show up all the time, otherwise it would be empty without any child tabs.

Agreed. But perhaps this could just be provided by `farm_settings` ? I do believe that the parent tab won't be displayed if there are no children tabs available or accessible (due to permissions). If it's possible for a "local task" to be provided that doesn't actually link to anything (there wouldn't be a canonical "notifications" page), then `farm_settings` could just provide the notification "Namespace" and let other modules populate it.

Docs for reference: https://www.drupal.org/docs/drupal-apis/menu-api/providing-module-defined-local-tasks#s-define-static-local-tasks

> route_name (required): The machine name of the local task route - this also determines where it's displayed.

Hmm but looks like a `route_name` is required. Not sure if there is a clever way to get around that... maybe we could make a dummy route of some sort? Even if it was simply "Select the tab for the type of notification you would like to configure." I think we would either need a canonical notification page of some sort or dynamic logic to make the Notification tab go to the lowest-weight notification tab that is provided. Hmmm. Any :bulb: ideas @Farmer-Eds-Shed @mstenta ?

_Alternatively...._ at one point I think we had discussed adding it as an Action Link on the data stream view tab. So when you're viewing a data stream, there could be a button "Configure notifications" in the top right. This would bring you to this page to configure *all* notifications, not only notifications for the single data stream, so perhaps that is confusing anyways.

2022-08-09 06:00 UTC, Farmer-Eds-Shed commented
> Interesting thanks for working on this

No Problem, It's a feature I want to use myself, so I felt it needs to go somewhere. 
> My first thought is that this seems a little weird in the Settings pages, but it's not awful

Yea, probably can't disagree, it's the least worst of the menu places I experimented with though 😆.

> _Alternatively...._ at one point I think we had discussed adding it as an Action Link on the data stream view tab. So when you're viewing a data stream, there could be a button "Configure notifications" in the top right. This would bring you to this page to configure _all_ notifications, not only notifications for the single data stream, so perhaps that is confusing anyways.

Not sure I like this one either as I agree it could be confusing, it would be better to link to notifications for the single data stream this way, but then it would still make sense for a notifications menu to manage all notifications.

> Hmm but looks like a `route_name` is required. Not sure if there is a clever way to get around that... maybe we could make a dummy route of some sort? Even if it was simply "Select the tab for the type of notification you would like to configure." I think we would either need a canonical notification page of some sort or dynamic logic to make the Notification tab go to the lowest-weight notification tab that is provided. Hmmm. Any 💡 idea

If creating an empty menu is an issue, then may be a basic notifications module is an option, similar to the data streams one but a little less obscure for the average user. I'd imagine the option of notifications for log creation/update could be popular and not weird to be activated alongside any other notification module that could be wanted in the future?  

I still propose using the settings menu for now if implementing the notifications menu may be a bit off,  as somewhere is better than nowhere, I opened the PR as I want to keep in line with farmOS without maintaining minor customizations on my server, but I can just as easily create a module to achieve the same. There are others interested in data streams but are probably unable to find this feature.

2022-08-10 19:02 UTC, paul121 commented
> I still propose using the settings menu for now if implementing the notifications menu may be a bit off, as somewhere is better than nowhere, I opened the PR as I want to keep in line with farmOS without maintaining minor customizations on my server, but I can just as easily create a module to achieve the same. There are others interested in data streams but are probably unable to find this feature.

Totally agree, thanks for expressing this. Given that this will only appear if that module is enabled, I agree that this is better than nowhere. In the future we could move this without it being a "breaking" change as well.

2022-08-10 19:05 UTC, paul121 approved these changes
I just wanted to review which permission is required to access this `entity.data_stream_notification.collection` route..

I believe it is this `access data_stream_notification overview` which we only grant to `config` roles, so this seems safe to me :+1: 

https://github.com/farmOS/farmOS/blob/fc77c86abe6b142702e7b103cd85e0c207333b79/modules/core/data_stream/modules/notification/data_stream_notification.managed_role_permissions.yml#L3

2022-08-12 12:13 UTC, mstenta commented
Thanks for reviewing @paul121! And all the good thoughts @Farmer-Eds-Shed!

>  may be a basic notifications module is an option

I started an initial branch for this on yesterday's dev call: https://github.com/mstenta/farmOS/tree/2.x-notification

We discussed that this core `farm_notification` module could eventually become the home for general notification logic (perhaps extracted/generalized from the `data_stream_notification` module). For now it just provides a "Notifications" tab under settings, which the data stream notification module can depend on.

I think I'll merge this, then rebase this PR on top and put the new menu link under that. Then we can look at generalizing the data stream notification code as a future step.

2022-08-12 13:22 UTC, mstenta commented
Updated screenshot:

![Screenshot from 2022-08-12 09-21-51](https://user-images.githubusercontent.com/95381/184362548-ea981e45-6843-472b-9539-e28b72baedef.png)

2022-08-12 15:56 UTC, paul121 requested changes

2022-08-12 15:56 UTC, paul121 commented on modules/core/notification/farm_notification.routing.yml
> +    _permission: 'administer farm notification'
I believe we need to add this to `managed_role_permissions` like here: https://github.com/farmOS/farmOS/blob/fc77c86abe6b142702e7b103cd85e0c207333b79/modules/core/data_stream/modules/notification/data_stream_notification.managed_role_permissions.yml#L3

2022-08-12 15:56 UTC, paul121 commented on modules/core/data_stream/modules/notification/data_stream_notification.info.yml
> +  - farm:farm_notification
I think we need an update hook to enable `farm_notification` on sites that already have `data_stream_notification` ?

2022-08-12 15:56 UTC, paul121 commented on modules/core/notification/src/Form/NotificationSettingsForm.php
> +      '#markup' => $this->t('Notification modules can add additional tabs to this page.'),
Could we add a prompt for the user? On mobile or small screens the tab options won't be visible. eg: "Select the tab for the type of notification to configure. Notification modules can add additional tabs to this page."

2022-08-15 13:27 UTC, mstenta commented
Thanks @paul121! Good eyes...

I made all the changes you requested in two "fixup" commits (to be squashed into the appropriate original commits before merging).

I also made one other small change: I made "Notifications" plural in the tab titles.

Requesting re-review before merge.

2022-08-15 13:28 UTC, mstenta commented
PS: I squashed the commits as described and pushed to a new `2.x-notification` branch if you want to see the final result: https://github.com/farmOS/farmOS/compare/2.x...mstenta:farmOS:2.x-notification

2022-08-15 15:42 UTC, paul121 approved these changes
LGTM!

2022-08-16 13:45 UTC, merged

2022-08-16 13:46 UTC, mstenta commented
Merged - thanks again @Farmer-Eds-Shed and @paul121!