fix map ui being unreadable on dark mode
farmOS/farmOS pull request #642
Opened 2023-02-20 18:32 UTC by wotnak

Fixes https://github.com/farmOS/farmOS/issues/641 by implementing solution proposed in the issue.

2023-02-20 20:39 UTC, symbioquine requested changes
CSS change looks good to me!

I think this just needs a [CHANGELOG.md](https://github.com/farmOS/farmOS/blame/18599f80c3d2e298a62aff276e10e3f898f22a66/CHANGELOG.md#L10) update and the PR number ("` #642`") added to the end of the git commit title.

2023-02-20 20:53 UTC, symbioquine approved these changes

2023-02-21 05:27 UTC, paul121 approved these changes
LGTM!

2023-02-21 15:47 UTC, merged

2023-02-21 15:47 UTC, mstenta commented
Merged. Thanks @wotnak!