Update composer.md guide to capture locked farmOS version
farmOS/farmOS pull request #697
Opened 2023-07-01 15:02 UTC by symbioquine

Having the version appear in the status report can be really helpful for debugging and improves the overall polish of these instructions IMHO :)

2023-07-02 14:36 UTC, mstenta requested changes
LGTM! Just one minor punctuation nit. :-)

2023-07-02 14:36 UTC, mstenta commented on docs/hosting/composer.md
> +# Install `jq` to help in extracting the farmOS version below
End comment with a period.

2023-07-03 13:13 UTC, symbioquine commented
Force push added the requested punctuation, added a changelog entry, and modified the commit message to include the PR #.

2023-07-04 12:22 UTC, merged

2023-07-04 12:22 UTC, mstenta commented
Merged - thanks @symbioquine!

2023-07-06 16:50 UTC, paul121 commented
It seems farmOS.org has not been updated with these changes: https://farmos.org/hosting/composer/#docker

I think the github action ran, but maybe the netlify build glitched? https://github.com/farmOS/farmOS/actions/runs/5454632918/jobs/9925013169

2023-07-07 16:53 UTC, wotnak commented
Looks like the Node.js version used for website build is too old. https://app.netlify.com/sites/gracious-brattain-bdd606/deploys/64a40f042600ba00081abaa6#L93
It can be configured in Netlify dashboard or using ntelify.toml file like I've done it in https://github.com/farmOS/farmOS.org/pull/79/files#diff-ab8f79b68b7adff7a07db953bf453f3c5aa6ade98d2b1b67d8432b36392489edR3.

2023-07-10 16:59 UTC, mstenta commented
FYI the issue was resolved by #79