Condense views table UI
farmOS/farmOS pull request #713
Opened 2023-08-25 23:19 UTC by paul121

General improvements to the views table UI, exposed filters, and condensing space on pages

2023-09-04 13:33 UTC, mstenta commented
Related discussion: https://farmos.discourse.group/t/ui-improvements-condensing-space/1732

2023-09-04 14:18 UTC, mstenta requested changes

2023-09-04 14:18 UTC, mstenta commented on modules/core/ui/views/config/install/views.view.farm_asset.yml
> +              empty_column: true
Do we want to set this on bundle-specific columns too? Currently this is only going to hide columns that are in the base View configuration, but we're also adding columns for bundle fields at runtime:

https://github.com/farmOS/farmOS/blob/399c01a177df14d4d2be547e28c6a98dee72fd63/modules/core/ui/views/farm_ui_views.views_execution.inc#L39

We aren't currently touching the `style.options.columns` configuration when we add columns in that hook, but maybe we should be - and without doing that it feels like this improvement is only half implemented. It wouldn't be obvious why some empty columns are hidden and others aren't.

2023-09-04 14:18 UTC, mstenta commented on modules/core/ui/theme/css/regions.css
> +/* Decrease the horizontal margin on medium to large screens. Gin uses xxl. */
I wonder if we should split this out to another PR so they can be considered separately? As is they would be hidden under the "Views"-specific `CHANGELOG.md` line.

2023-09-07 17:57 UTC, paul121 commented on modules/core/ui/views/config/install/views.view.farm_asset.yml
> +              empty_column: true
Agreed

2023-09-07 18:04 UTC, paul121 commented on modules/core/ui/theme/css/regions.css
> +/* Decrease the horizontal margin on medium to large screens. Gin uses xxl. */
Yes - split to here https://github.com/farmOS/farmOS/pull/719

2023-09-07 18:30 UTC, paul121 commented on modules/core/ui/views/config/install/views.view.farm_asset.yml
> +              empty_column: true
This was pretty easy! Also added a commit to let bundle fields be sortable.

2023-10-05 14:51 UTC, mstenta approved these changes

2023-10-06 18:41 UTC, merged