Add bulk delete action to farm_log_quantity View
farmOS/farmOS pull request #860
Opened 2024-07-26 16:27 UTC by mstenta

This PR adds a "Delete" action for quantity entities, and adds a "Bulk update" column to the `farm_log_quantity` View, allowing users to delete quantities in bulk across multiple logs.

Note that this PR builds on top of #858 (so that needs to be merged first). We should also merge #859 before this, to ensure references to deleted quantities are cleaned up.

This is also a pre-step towards adding a new "Export CSV" bulk action to the `farm_log_quantity` View. We need to add the "Bulk update" column to the `farm_log_quantity` View in order for that new "Export CSV" action to show up (without explicitly depending on the `farm_export_csv` module), but the Drupal core Views module does not make a "Bulk update" column available unless there are bulk actions available for the entity type. Right now, `quantity` entities do not have any bulk actions available. So by adding a "delete" action, we both get a new feature (ability to delete quantities in bulk), and we make it easier to add new actions in next steps.

2024-07-26 16:37 UTC, mstenta commented
Adding this to the v3.3.0 milestone since it is a new feature.

2024-07-26 20:06 UTC, paul121 requested changes
This works great! One thing to note is that the delete confirmation form displays `$quantity->label()` but this only returns the quantity ID. I think we should update the `$quantity->label()` method to return the 'rendered quantity' in the default template where we've already implemented the logic for displaying base and bundle quantity fields.

```php
  /**
   * {@inheritdoc}
   */
  public function label() {
    $view_builder = \Drupal::entityTypeManager()->getViewBuilder($this->entityTypeId);
    $renderable = $view_builder->view($this);
    return \Drupal::service('renderer')->renderPlain($renderable);
  }
```

If we don't want to modify the label function I think we could accomplish this same thing by implementing a custom `QuantityDeleteForm`. With a custom form it could be nice to display some info about the log the quantity is associated with, too. Maybe even group multiple quantities in a nested list under their respective log. 

Screenshots for reference:
![quantity-id-delete](https://github.com/user-attachments/assets/44a2ef1b-a52f-424c-84d8-ac4e5bf580a7)

![quantity-label-delete](https://github.com/user-attachments/assets/583b9c44-20fe-4b79-9768-27ea19c3244f)

2024-07-29 15:44 UTC, mstenta commented
> I think we should update the `$quantity->label()` method to return the 'rendered quantity' in the default template 

This seems sensible to me. I wonder if that label gets used anywhere else. I can't think of anything.

@paul121 Could you add that as a separate commit in this branch and push so we can see if it breaks any tests?

2024-07-29 18:16 UTC, paul121 commented
> @paul121 Could you add that as a separate commit in this branch and push so we can see if it breaks any tests?

Done and looks like tests passed

2024-07-29 18:42 UTC, mstenta commented
Thanks @paul121! I think this is ready to merge.

2024-07-29 18:51 UTC, paul121 approved these changes

2024-09-23 18:00 UTC, merged